# **Fundamentos de RL**
## **Regresión Logística**

### Librerías

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

### Cargar dataset


Diabetics prediction using logistic regression

https://www.kaggle.com/datasets/kandij/diabetes-dataset

In [46]:
data = pd.read_csv(filepath_or_buffer='https://raw.githubusercontent.com/cdavid2804/test-1/main/diabetes2.csv')
print("Número de datos originales:",np.shape(data))
# Eliminar datos que tienen "nan"
data = data.dropna()
print("Número de datos filtrado:",np.shape(data))
data.head(10)

Número de datos originales: (768, 9)
Número de datos filtrado: (768, 9)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

## **Algoritmo**

### Matriz de correlación entre variables

In [47]:
data.corr()# data conunto de datos donde se almacena el dataset, corr es la matriz de correlación. valor mayor a 1 significa mas correlacion

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
Glucose,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
BloodPressure,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
SkinThickness,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
Insulin,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
BMI,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
DiabetesPedigreeFunction,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
Age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
Outcome,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

### División de los datos (entrenamiento y prueba)
#### Agregar una vector columna de "$1$" a $X$ (coeficiente de intersección)

$$X=\begin{bmatrix}
x_{11} & x_{12} & \cdots & x_{1n} \\
x_{21} & x_{22} & \cdots & x_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
x_{m1} & x_{m2} & \cdots & x_{mn}  
\end{bmatrix}\rightarrow X=\begin{bmatrix}
1 & x_{11} & x_{12} & \cdots & x_{1n} \\
1 & x_{21} & x_{22} & \cdots & x_{2n} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
1 & x_{m1} & x_{m2} & \cdots & x_{mn}  
\end{bmatrix}$$

In [35]:
# caracteristicas extraidas de forma de matriz convertida en arreglo
X = data[['Pregnancies','Glucose','Insulin','BloodPressure','SkinThickness']]
y = data['Outcome']
X = X.values# almacena valor de entrada
y = y.values# almacena valor de salida

### Normalización de los datos
$$ X_{norm} = \frac{X - \mu}{\sigma} $$

- $\mu$: media
- $\sigma$: desviación estándar

$$ X_{norm} = \frac{X - X_{min}}{X_{max}-X_{min}} $$

- $X_{max}$: valor máximo
- $X_{min}$: valor mínimo

In [36]:
X_norm = (X - np.mean(X, axis = 0)) / np.std(X, axis = 0)
#np.mean saca media y np.std saca desviacion estandar
X_norm = np.hstack((np.ones((X_norm.shape[0],1)), X_norm))

#Division de datos
X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size = 0.15)
print(f"Training data: {np.shape(X_train)}")
print(f"Test data: {np.shape(X_test)}")

Training data: (652, 6)
Test data: (116, 6)

### Definir la función sigmoidea

$$\sigma(z)=\displaystyle\frac{1}{1+e^{-z}}$$

In [37]:
def sigmoid(z):
  s = 1 / (1 + np.exp(-z))# np.exp para colocar exponencial euler
  return s

### Definir la función de pérdida

$$loss = -\displaystyle\frac{1}{m}\displaystyle\sum_{i=1}^m\left[y\ln(h_{\theta})+(1-y)\ln(1-h_{\theta})\right] $$

$$h_{\theta} = \sigma(z)$$

In [38]:
def loss(h, y):
  lss = (-(y*np.log(h) + (1-y) * np.log(1 - h))).mean()
  return lss

### Descenso del gradiente

$$
\begin{align}
&\begin{array}{l}
\hline
\textbf{Algorithm:}\text{ Gradient Descent for Logistic Regression } \\
\hline
\textbf{Input:} \\
1: \hspace{3mm} \text{Train set} {(X_1,y_1),...,(X_n,y_n)},  \\
2: \hspace{3mm} \text{Learning rate } \alpha > 0, \\
3: \hspace{3mm} \text{Number of iterations T},  \\
4: \hspace{3mm} \text{Initial weights }\theta  \\
5: \hspace{3mm} \textbf{for } t=1,2,...,T \textbf{ do}\\
6: \hspace{10mm} \text{Calcualte value of objective function: } z=X.\theta \\
7: \hspace{10mm} \text{Calcualte sigmoid function: } h_{\theta}=\sigma(z) \\
8: \hspace{10mm} \text{Compute gradients: } \triangledown_{\theta}J(\theta)=\displaystyle\frac{1}{m}X^{T}(h_{\theta}-y) \\
9: \hspace{10mm} \text{Update weights: } \theta_{update} =\theta - \alpha\triangledown_{\theta}J(\theta) \\
10: \hspace{2mm} \textbf{end for} \\
11: \hspace{2mm} \textbf{return} \text{ Output: extract weights } \theta \\
\hline
\end{array}
\end{align}
$$

In [39]:
def logistic_regression(X, y, alpha, t):
  theta = np.random.rand(X.shape[1])

  for i in range(t):
    m = y.size
    z = np.dot(X, theta)
    h = sigmoid(z)
    gradient = np.dot(X.T, (h-y)) / m
    theta = theta - alpha * gradient

    if (i%100) == 0:
      print(f"Iteration {i}, Loss: {loss(h, y):.4f}")

  return theta

alpha = 0.001
num_iterations = 100000
np.random.seed(23)
theta = logistic_regression(X_train, y_train, alpha, num_iterations)

Iteration 0, Loss: 0.7403
Iteration 100, Loss: 0.7332
Iteration 200, Loss: 0.7262
Iteration 300, Loss: 0.7195
Iteration 400, Loss: 0.7129
Iteration 500, Loss: 0.7066
Iteration 600, Loss: 0.7004
Iteration 700, Loss: 0.6944
Iteration 800, Loss: 0.6885
Iteration 900, Loss: 0.6829
Iteration 1000, Loss: 0.6774
Iteration 1100, Loss: 0.6720
Iteration 1200, Loss: 0.6668
Iteration 1300, Loss: 0.6618
Iteration 1400, Loss: 0.6569
Iteration 1500, Loss: 0.6522
Iteration 1600, Loss: 0.6476
Iteration 1700, Loss: 0.6431
Iteration 1800, Loss: 0.6388
Iteration 1900, Loss: 0.6346
Iteration 2000, Loss: 0.6305
Iteration 2100, Loss: 0.6266
Iteration 2200, Loss: 0.6228
Iteration 2300, Loss: 0.6191
Iteration 2400, Loss: 0.6155
Iteration 2500, Loss: 0.6121
Iteration 2600, Loss: 0.6087
Iteration 2700, Loss: 0.6055
Iteration 2800, Loss: 0.6023
Iteration 2900, Loss: 0.5993
Iteration 3000, Loss: 0.5964
Iteration 3100, Loss: 0.5935
Iteration 3200, Loss: 0.5908
Iteration 3300, Loss: 0.5881
Iteration 3400, Loss: 0.5855
Iteration 3500, Loss: 0.5831
Iteration 3600, Loss: 0.5807
Iteration 3700, Loss: 0.5783
Iteration 3800, Loss: 0.5761
Iteration 3900, Loss: 0.5739
Iteration 4000, Loss: 0.5718
Iteration 4100, Loss: 0.5698
Iteration 4200, Loss: 0.5679
Iteration 4300, Loss: 0.5660
Iteration 4400, Loss: 0.5642
Iteration 4500, Loss: 0.5624
Iteration 4600, Loss: 0.5607
Iteration 4700, Loss: 0.5591
Iteration 4800, Loss: 0.5575
Iteration 4900, Loss: 0.5560
Iteration 5000, Loss: 0.5545
Iteration 5100, Loss: 0.5531
Iteration 5200, Loss: 0.5518
Iteration 5300, Loss: 0.5504
Iteration 5400, Loss: 0.5492
Iteration 5500, Loss: 0.5480
Iteration 5600, Loss: 0.5468
Iteration 5700, Loss: 0.5456
Iteration 5800, Loss: 0.5445
Iteration 5900, Loss: 0.5435
Iteration 6000, Loss: 0.5425
Iteration 6100, Loss: 0.5415
Iteration 6200, Loss: 0.5405
Iteration 6300, Loss: 0.5396
Iteration 6400, Loss: 0.5387
Iteration 6500, Loss: 0.5379
Iteration 6600, Loss: 0.5371
Iteration 6700, Loss: 0.5363
Iteration 6800, Loss: 0.5355
Iteration 6900, Loss: 0.5348
Iteration 7000, Loss: 0.5341
Iteration 7100, Loss: 0.5334
Iteration 7200, Loss: 0.5327
Iteration 7300, Loss: 0.5321
Iteration 7400, Loss: 0.5315
Iteration 7500, Loss: 0.5309
Iteration 7600, Loss: 0.5304
Iteration 7700, Loss: 0.5298
Iteration 7800, Loss: 0.5293
Iteration 7900, Loss: 0.5288
Iteration 8000, Loss: 0.5283
Iteration 8100, Loss: 0.5278
Iteration 8200, Loss: 0.5274
Iteration 8300, Loss: 0.5269
Iteration 8400, Loss: 0.5265
Iteration 8500, Loss: 0.5261
Iteration 8600, Loss: 0.5257
Iteration 8700, Loss: 0.5253
Iteration 8800, Loss: 0.5250
Iteration 8900, Loss: 0.5246
Iteration 9000, Loss: 0.5243
Iteration 9100, Loss: 0.5240
Iteration 9200, Loss: 0.5236
Iteration 9300, Loss: 0.5233
Iteration 9400, Loss: 0.5230
Iteration 9500, Loss: 0.5228
Iteration 9600, Loss: 0.5225
Iteration 9700, Loss: 0.5222
Iteration 9800, Loss: 0.5220
Iteration 9900, Loss: 0.5217
Iteration 10000, Loss: 0.5215
Iteration 10100, Loss: 0.5213
Iteration 10200, Loss: 0.5210
Iteration 10300, Loss: 0.5208
Iteration 10400, Loss: 0.5206
Iteration 10500, Loss: 0.5204
Iteration 10600, Loss: 0.5202
Iteration 10700, Loss: 0.5201
Iteration 10800, Loss: 0.5199
Iteration 10900, Loss: 0.5197
Iteration 11000, Loss: 0.5195
Iteration 11100, Loss: 0.5194
Iteration 11200, Loss: 0.5192
Iteration 11300, Loss: 0.5191
Iteration 11400, Loss: 0.5189
Iteration 11500, Loss: 0.5188
Iteration 11600, Loss: 0.5187
Iteration 11700, Loss: 0.5185
Iteration 11800, Loss: 0.5184
Iteration 11900, Loss: 0.5183
Iteration 12000, Loss: 0.5182
Iteration 12100, Loss: 0.5180
Iteration 12200, Loss: 0.5179
Iteration 12300, Loss: 0.5178
Iteration 12400, Loss: 0.5177
Iteration 12500, Loss: 0.5176
Iteration 12600, Loss: 0.5175
Iteration 12700, Loss: 0.5174
Iteration 12800, Loss: 0.5173
Iteration 12900, Loss: 0.5173
Iteration 13000, Loss: 0.5172
Iteration 13100, Loss: 0.5171
Iteration 13200, Loss: 0.5170
Iteration 13300, Loss: 0.5169
Iteration 13400, Loss: 0.5169
Iteration 13500, Loss: 0.5168
Iteration 13600, Loss: 0.5167
Iteration 13700, Loss: 0.5167
Iteration 13800, Loss: 0.5166
Iteration 13900, Loss: 0.5165
Iteration 14000, Loss: 0.5165
Iteration 14100, Loss: 0.5164
Iteration 14200, Loss: 0.5163
Iteration 14300, Loss: 0.5163
Iteration 14400, Loss: 0.5162
Iteration 14500, Loss: 0.5162
Iteration 14600, Loss: 0.5161
Iteration 14700, Loss: 0.5161
Iteration 14800, Loss: 0.5160
Iteration 14900, Loss: 0.5160
Iteration 15000, Loss: 0.5159
Iteration 15100, Loss: 0.5159
Iteration 15200, Loss: 0.5159
Iteration 15300, Loss: 0.5158
Iteration 15400, Loss: 0.5158
Iteration 15500, Loss: 0.5157
Iteration 15600, Loss: 0.5157
Iteration 15700, Loss: 0.5157
Iteration 15800, Loss: 0.5156
Iteration 15900, Loss: 0.5156
Iteration 16000, Loss: 0.5156
Iteration 16100, Loss: 0.5155
Iteration 16200, Loss: 0.5155
Iteration 16300, Loss: 0.5155
Iteration 16400, Loss: 0.5154
Iteration 16500, Loss: 0.5154
Iteration 16600, Loss: 0.5154
Iteration 16700, Loss: 0.5154
Iteration 16800, Loss: 0.5153
Iteration 16900, Loss: 0.5153
Iteration 17000, Loss: 0.5153
Iteration 17100, Loss: 0.5153
Iteration 17200, Loss: 0.5152
Iteration 17300, Loss: 0.5152
Iteration 17400, Loss: 0.5152
Iteration 17500, Loss: 0.5152
Iteration 17600, Loss: 0.5151
Iteration 17700, Loss: 0.5151
Iteration 17800, Loss: 0.5151
Iteration 17900, Loss: 0.5151
Iteration 18000, Loss: 0.5151
Iteration 18100, Loss: 0.5150
Iteration 18200, Loss: 0.5150
Iteration 18300, Loss: 0.5150
Iteration 18400, Loss: 0.5150
Iteration 18500, Loss: 0.5150
Iteration 18600, Loss: 0.5150
Iteration 18700, Loss: 0.5149
Iteration 18800, Loss: 0.5149
Iteration 18900, Loss: 0.5149
Iteration 19000, Loss: 0.5149
Iteration 19100, Loss: 0.5149
Iteration 19200, Loss: 0.5149
Iteration 19300, Loss: 0.5149
Iteration 19400, Loss: 0.5148
Iteration 19500, Loss: 0.5148
Iteration 19600, Loss: 0.5148
Iteration 19700, Loss: 0.5148
Iteration 19800, Loss: 0.5148
Iteration 19900, Loss: 0.5148
Iteration 20000, Loss: 0.5148
Iteration 20100, Loss: 0.5148
Iteration 20200, Loss: 0.5148
Iteration 20300, Loss: 0.5147
Iteration 20400, Loss: 0.5147
Iteration 20500, Loss: 0.5147
Iteration 20600, Loss: 0.5147
Iteration 20700, Loss: 0.5147
Iteration 20800, Loss: 0.5147
Iteration 20900, Loss: 0.5147
Iteration 21000, Loss: 0.5147
Iteration 21100, Loss: 0.5147
Iteration 21200, Loss: 0.5147
Iteration 21300, Loss: 0.5147
Iteration 21400, Loss: 0.5146
Iteration 21500, Loss: 0.5146
Iteration 21600, Loss: 0.5146
Iteration 21700, Loss: 0.5146
Iteration 21800, Loss: 0.5146
Iteration 21900, Loss: 0.5146
Iteration 22000, Loss: 0.5146
Iteration 22100, Loss: 0.5146
Iteration 22200, Loss: 0.5146
Iteration 22300, Loss: 0.5146
Iteration 22400, Loss: 0.5146
Iteration 22500, Loss: 0.5146
Iteration 22600, Loss: 0.5146
Iteration 22700, Loss: 0.5146
Iteration 22800, Loss: 0.5146
Iteration 22900, Loss: 0.5145
Iteration 23000, Loss: 0.5145
Iteration 23100, Loss: 0.5145
Iteration 23200, Loss: 0.5145
Iteration 23300, Loss: 0.5145
Iteration 23400, Loss: 0.5145
Iteration 23500, Loss: 0.5145
Iteration 23600, Loss: 0.5145
Iteration 23700, Loss: 0.5145
Iteration 23800, Loss: 0.5145
Iteration 23900, Loss: 0.5145
Iteration 24000, Loss: 0.5145
Iteration 24100, Loss: 0.5145
Iteration 24200, Loss: 0.5145
Iteration 24300, Loss: 0.5145
Iteration 24400, Loss: 0.5145
Iteration 24500, Loss: 0.5145
Iteration 24600, Loss: 0.5145
Iteration 24700, Loss: 0.5145
Iteration 24800, Loss: 0.5145
Iteration 24900, Loss: 0.5145
Iteration 25000, Loss: 0.5145
Iteration 25100, Loss: 0.5145
Iteration 25200, Loss: 0.5144
Iteration 25300, Loss: 0.5144
Iteration 25400, Loss: 0.5144
Iteration 25500, Loss: 0.5144
Iteration 25600, Loss: 0.5144
Iteration 25700, Loss: 0.5144
Iteration 25800, Loss: 0.5144
Iteration 25900, Loss: 0.5144
Iteration 26000, Loss: 0.5144
Iteration 26100, Loss: 0.5144
Iteration 26200, Loss: 0.5144
Iteration 26300, Loss: 0.5144
Iteration 26400, Loss: 0.5144
Iteration 26500, Loss: 0.5144
Iteration 26600, Loss: 0.5144
Iteration 26700, Loss: 0.5144
Iteration 26800, Loss: 0.5144
Iteration 26900, Loss: 0.5144
Iteration 27000, Loss: 0.5144
Iteration 27100, Loss: 0.5144
Iteration 27200, Loss: 0.5144
Iteration 27300, Loss: 0.5144
Iteration 27400, Loss: 0.5144
Iteration 27500, Loss: 0.5144
Iteration 27600, Loss: 0.5144
Iteration 27700, Loss: 0.5144
Iteration 27800, Loss: 0.5144
Iteration 27900, Loss: 0.5144
Iteration 28000, Loss: 0.5144
Iteration 28100, Loss: 0.5144
Iteration 28200, Loss: 0.5144
Iteration 28300, Loss: 0.5144
Iteration 28400, Loss: 0.5144
Iteration 28500, Loss: 0.5144
Iteration 28600, Loss: 0.5144
Iteration 28700, Loss: 0.5144
Iteration 28800, Loss: 0.5144
Iteration 28900, Loss: 0.5144
Iteration 29000, Loss: 0.5144
Iteration 29100, Loss: 0.5144
Iteration 29200, Loss: 0.5144
Iteration 29300, Loss: 0.5144
Iteration 29400, Loss: 0.5144
Iteration 29500, Loss: 0.5144
Iteration 29600, Loss: 0.5144
Iteration 29700, Loss: 0.5144
Iteration 29800, Loss: 0.5144
Iteration 29900, Loss: 0.5144
Iteration 30000, Loss: 0.5144
Iteration 30100, Loss: 0.5144
Iteration 30200, Loss: 0.5144
Iteration 30300, Loss: 0.5144
Iteration 30400, Loss: 0.5143
Iteration 30500, Loss: 0.5143
Iteration 30600, Loss: 0.5143
Iteration 30700, Loss: 0.5143
Iteration 30800, Loss: 0.5143
Iteration 30900, Loss: 0.5143
Iteration 31000, Loss: 0.5143
Iteration 31100, Loss: 0.5143
Iteration 31200, Loss: 0.5143
Iteration 31300, Loss: 0.5143
Iteration 31400, Loss: 0.5143
Iteration 31500, Loss: 0.5143
Iteration 31600, Loss: 0.5143
Iteration 31700, Loss: 0.5143
Iteration 31800, Loss: 0.5143
Iteration 31900, Loss: 0.5143
Iteration 32000, Loss: 0.5143
Iteration 32100, Loss: 0.5143
Iteration 32200, Loss: 0.5143
Iteration 32300, Loss: 0.5143
Iteration 32400, Loss: 0.5143
Iteration 32500, Loss: 0.5143
Iteration 32600, Loss: 0.5143
Iteration 32700, Loss: 0.5143
Iteration 32800, Loss: 0.5143
Iteration 32900, Loss: 0.5143
Iteration 33000, Loss: 0.5143
Iteration 33100, Loss: 0.5143
Iteration 33200, Loss: 0.5143
Iteration 33300, Loss: 0.5143
Iteration 33400, Loss: 0.5143
Iteration 33500, Loss: 0.5143
Iteration 33600, Loss: 0.5143
Iteration 33700, Loss: 0.5143
Iteration 33800, Loss: 0.5143
Iteration 33900, Loss: 0.5143
Iteration 34000, Loss: 0.5143
Iteration 34100, Loss: 0.5143
Iteration 34200, Loss: 0.5143
Iteration 34300, Loss: 0.5143
Iteration 34400, Loss: 0.5143
Iteration 34500, Loss: 0.5143
Iteration 34600, Loss: 0.5143
Iteration 34700, Loss: 0.5143
Iteration 34800, Loss: 0.5143
Iteration 34900, Loss: 0.5143
Iteration 35000, Loss: 0.5143
Iteration 35100, Loss: 0.5143
Iteration 35200, Loss: 0.5143
Iteration 35300, Loss: 0.5143
Iteration 35400, Loss: 0.5143
Iteration 35500, Loss: 0.5143
Iteration 35600, Loss: 0.5143
Iteration 35700, Loss: 0.5143
Iteration 35800, Loss: 0.5143
Iteration 35900, Loss: 0.5143
Iteration 36000, Loss: 0.5143
Iteration 36100, Loss: 0.5143
Iteration 36200, Loss: 0.5143
Iteration 36300, Loss: 0.5143
Iteration 36400, Loss: 0.5143
Iteration 36500, Loss: 0.5143
Iteration 36600, Loss: 0.5143
Iteration 36700, Loss: 0.5143
Iteration 36800, Loss: 0.5143
Iteration 36900, Loss: 0.5143
Iteration 37000, Loss: 0.5143
Iteration 37100, Loss: 0.5143
Iteration 37200, Loss: 0.5143
Iteration 37300, Loss: 0.5143
Iteration 37400, Loss: 0.5143
Iteration 37500, Loss: 0.5143
Iteration 37600, Loss: 0.5143
Iteration 37700, Loss: 0.5143
Iteration 37800, Loss: 0.5143
Iteration 37900, Loss: 0.5143
Iteration 38000, Loss: 0.5143
Iteration 38100, Loss: 0.5143
Iteration 38200, Loss: 0.5143
Iteration 38300, Loss: 0.5143
Iteration 38400, Loss: 0.5143
Iteration 38500, Loss: 0.5143
Iteration 38600, Loss: 0.5143
Iteration 38700, Loss: 0.5143
Iteration 38800, Loss: 0.5143
Iteration 38900, Loss: 0.5143
Iteration 39000, Loss: 0.5143
Iteration 39100, Loss: 0.5143
Iteration 39200, Loss: 0.5143
Iteration 39300, Loss: 0.5143
Iteration 39400, Loss: 0.5143
Iteration 39500, Loss: 0.5143
Iteration 39600, Loss: 0.5143
Iteration 39700, Loss: 0.5143
Iteration 39800, Loss: 0.5143
Iteration 39900, Loss: 0.5143
Iteration 40000, Loss: 0.5143
Iteration 40100, Loss: 0.5143
Iteration 40200, Loss: 0.5143
Iteration 40300, Loss: 0.5143
Iteration 40400, Loss: 0.5143
Iteration 40500, Loss: 0.5143
Iteration 40600, Loss: 0.5143
Iteration 40700, Loss: 0.5143
Iteration 40800, Loss: 0.5143
Iteration 40900, Loss: 0.5143
Iteration 41000, Loss: 0.5143
Iteration 41100, Loss: 0.5143
Iteration 41200, Loss: 0.5143
Iteration 41300, Loss: 0.5143
Iteration 41400, Loss: 0.5143
Iteration 41500, Loss: 0.5143
Iteration 41600, Loss: 0.5143
Iteration 41700, Loss: 0.5143
Iteration 41800, Loss: 0.5143
Iteration 41900, Loss: 0.5143
Iteration 42000, Loss: 0.5143
Iteration 42100, Loss: 0.5143
Iteration 42200, Loss: 0.5143
Iteration 42300, Loss: 0.5143
Iteration 42400, Loss: 0.5143
Iteration 42500, Loss: 0.5143
Iteration 42600, Loss: 0.5143
Iteration 42700, Loss: 0.5143
Iteration 42800, Loss: 0.5143
Iteration 42900, Loss: 0.5143
Iteration 43000, Loss: 0.5143
Iteration 43100, Loss: 0.5143
Iteration 43200, Loss: 0.5143
Iteration 43300, Loss: 0.5143
Iteration 43400, Loss: 0.5143
Iteration 43500, Loss: 0.5143
Iteration 43600, Loss: 0.5143
Iteration 43700, Loss: 0.5143
Iteration 43800, Loss: 0.5143
Iteration 43900, Loss: 0.5143
Iteration 44000, Loss: 0.5143
Iteration 44100, Loss: 0.5143
Iteration 44200, Loss: 0.5143
Iteration 44300, Loss: 0.5143
Iteration 44400, Loss: 0.5143
Iteration 44500, Loss: 0.5143
Iteration 44600, Loss: 0.5143
Iteration 44700, Loss: 0.5143
Iteration 44800, Loss: 0.5143
Iteration 44900, Loss: 0.5143
Iteration 45000, Loss: 0.5143
Iteration 45100, Loss: 0.5143
Iteration 45200, Loss: 0.5143
Iteration 45300, Loss: 0.5143
Iteration 45400, Loss: 0.5143
Iteration 45500, Loss: 0.5143
Iteration 45600, Loss: 0.5143
Iteration 45700, Loss: 0.5143
Iteration 45800, Loss: 0.5143
Iteration 45900, Loss: 0.5143
Iteration 46000, Loss: 0.5143
Iteration 46100, Loss: 0.5143
Iteration 46200, Loss: 0.5143
Iteration 46300, Loss: 0.5143
Iteration 46400, Loss: 0.5143
Iteration 46500, Loss: 0.5143
Iteration 46600, Loss: 0.5143
Iteration 46700, Loss: 0.5143
Iteration 46800, Loss: 0.5143
Iteration 46900, Loss: 0.5143
Iteration 47000, Loss: 0.5143
Iteration 47100, Loss: 0.5143
Iteration 47200, Loss: 0.5143
Iteration 47300, Loss: 0.5143
Iteration 47400, Loss: 0.5143
Iteration 47500, Loss: 0.5143
Iteration 47600, Loss: 0.5143
Iteration 47700, Loss: 0.5143
Iteration 47800, Loss: 0.5143
Iteration 47900, Loss: 0.5143
Iteration 48000, Loss: 0.5143
Iteration 48100, Loss: 0.5143
Iteration 48200, Loss: 0.5143
Iteration 48300, Loss: 0.5143
Iteration 48400, Loss: 0.5143
Iteration 48500, Loss: 0.5143
Iteration 48600, Loss: 0.5143
Iteration 48700, Loss: 0.5143
Iteration 48800, Loss: 0.5143
Iteration 48900, Loss: 0.5143
Iteration 49000, Loss: 0.5143
Iteration 49100, Loss: 0.5143
Iteration 49200, Loss: 0.5143
Iteration 49300, Loss: 0.5143
Iteration 49400, Loss: 0.5143
Iteration 49500, Loss: 0.5143
Iteration 49600, Loss: 0.5143
Iteration 49700, Loss: 0.5143
Iteration 49800, Loss: 0.5143
Iteration 49900, Loss: 0.5143
Iteration 50000, Loss: 0.5143
Iteration 50100, Loss: 0.5143
Iteration 50200, Loss: 0.5143
Iteration 50300, Loss: 0.5143
Iteration 50400, Loss: 0.5143
Iteration 50500, Loss: 0.5143
Iteration 50600, Loss: 0.5143
Iteration 50700, Loss: 0.5143
Iteration 50800, Loss: 0.5143
Iteration 50900, Loss: 0.5143
Iteration 51000, Loss: 0.5143
Iteration 51100, Loss: 0.5143
Iteration 51200, Loss: 0.5143
Iteration 51300, Loss: 0.5143
Iteration 51400, Loss: 0.5143
Iteration 51500, Loss: 0.5143
Iteration 51600, Loss: 0.5143
Iteration 51700, Loss: 0.5143
Iteration 51800, Loss: 0.5143
Iteration 51900, Loss: 0.5143
Iteration 52000, Loss: 0.5143
Iteration 52100, Loss: 0.5143
Iteration 52200, Loss: 0.5143
Iteration 52300, Loss: 0.5143
Iteration 52400, Loss: 0.5143
Iteration 52500, Loss: 0.5143
Iteration 52600, Loss: 0.5143
Iteration 52700, Loss: 0.5143
Iteration 52800, Loss: 0.5143
Iteration 52900, Loss: 0.5143
Iteration 53000, Loss: 0.5143
Iteration 53100, Loss: 0.5143
Iteration 53200, Loss: 0.5143
Iteration 53300, Loss: 0.5143
Iteration 53400, Loss: 0.5143
Iteration 53500, Loss: 0.5143
Iteration 53600, Loss: 0.5143
Iteration 53700, Loss: 0.5143
Iteration 53800, Loss: 0.5143
Iteration 53900, Loss: 0.5143
Iteration 54000, Loss: 0.5143
Iteration 54100, Loss: 0.5143
Iteration 54200, Loss: 0.5143
Iteration 54300, Loss: 0.5143
Iteration 54400, Loss: 0.5143
Iteration 54500, Loss: 0.5143
Iteration 54600, Loss: 0.5143
Iteration 54700, Loss: 0.5143
Iteration 54800, Loss: 0.5143
Iteration 54900, Loss: 0.5143
Iteration 55000, Loss: 0.5143
Iteration 55100, Loss: 0.5143
Iteration 55200, Loss: 0.5143
Iteration 55300, Loss: 0.5143
Iteration 55400, Loss: 0.5143
Iteration 55500, Loss: 0.5143
Iteration 55600, Loss: 0.5143
Iteration 55700, Loss: 0.5143
Iteration 55800, Loss: 0.5143
Iteration 55900, Loss: 0.5143
Iteration 56000, Loss: 0.5143
Iteration 56100, Loss: 0.5143
Iteration 56200, Loss: 0.5143
Iteration 56300, Loss: 0.5143
Iteration 56400, Loss: 0.5143
Iteration 56500, Loss: 0.5143
Iteration 56600, Loss: 0.5143
Iteration 56700, Loss: 0.5143
Iteration 56800, Loss: 0.5143
Iteration 56900, Loss: 0.5143
Iteration 57000, Loss: 0.5143
Iteration 57100, Loss: 0.5143
Iteration 57200, Loss: 0.5143
Iteration 57300, Loss: 0.5143
Iteration 57400, Loss: 0.5143
Iteration 57500, Loss: 0.5143
Iteration 57600, Loss: 0.5143
Iteration 57700, Loss: 0.5143
Iteration 57800, Loss: 0.5143
Iteration 57900, Loss: 0.5143
Iteration 58000, Loss: 0.5143
Iteration 58100, Loss: 0.5143
Iteration 58200, Loss: 0.5143
Iteration 58300, Loss: 0.5143
Iteration 58400, Loss: 0.5143
Iteration 58500, Loss: 0.5143
Iteration 58600, Loss: 0.5143
Iteration 58700, Loss: 0.5143
Iteration 58800, Loss: 0.5143
Iteration 58900, Loss: 0.5143
Iteration 59000, Loss: 0.5143
Iteration 59100, Loss: 0.5143
Iteration 59200, Loss: 0.5143
Iteration 59300, Loss: 0.5143
Iteration 59400, Loss: 0.5143
Iteration 59500, Loss: 0.5143
Iteration 59600, Loss: 0.5143
Iteration 59700, Loss: 0.5143
Iteration 59800, Loss: 0.5143
Iteration 59900, Loss: 0.5143
Iteration 60000, Loss: 0.5143
Iteration 60100, Loss: 0.5143
Iteration 60200, Loss: 0.5143
Iteration 60300, Loss: 0.5143
Iteration 60400, Loss: 0.5143
Iteration 60500, Loss: 0.5143
Iteration 60600, Loss: 0.5143
Iteration 60700, Loss: 0.5143
Iteration 60800, Loss: 0.5143
Iteration 60900, Loss: 0.5143
Iteration 61000, Loss: 0.5143
Iteration 61100, Loss: 0.5143
Iteration 61200, Loss: 0.5143
Iteration 61300, Loss: 0.5143
Iteration 61400, Loss: 0.5143
Iteration 61500, Loss: 0.5143
Iteration 61600, Loss: 0.5143
Iteration 61700, Loss: 0.5143
Iteration 61800, Loss: 0.5143
Iteration 61900, Loss: 0.5143
Iteration 62000, Loss: 0.5143
Iteration 62100, Loss: 0.5143
Iteration 62200, Loss: 0.5143
Iteration 62300, Loss: 0.5143
Iteration 62400, Loss: 0.5143
Iteration 62500, Loss: 0.5143
Iteration 62600, Loss: 0.5143
Iteration 62700, Loss: 0.5143
Iteration 62800, Loss: 0.5143
Iteration 62900, Loss: 0.5143
Iteration 63000, Loss: 0.5143
Iteration 63100, Loss: 0.5143
Iteration 63200, Loss: 0.5143
Iteration 63300, Loss: 0.5143
Iteration 63400, Loss: 0.5143
Iteration 63500, Loss: 0.5143
Iteration 63600, Loss: 0.5143
Iteration 63700, Loss: 0.5143
Iteration 63800, Loss: 0.5143
Iteration 63900, Loss: 0.5143
Iteration 64000, Loss: 0.5143
Iteration 64100, Loss: 0.5143
Iteration 64200, Loss: 0.5143
Iteration 64300, Loss: 0.5143
Iteration 64400, Loss: 0.5143
Iteration 64500, Loss: 0.5143
Iteration 64600, Loss: 0.5143
Iteration 64700, Loss: 0.5143
Iteration 64800, Loss: 0.5143
Iteration 64900, Loss: 0.5143
Iteration 65000, Loss: 0.5143
Iteration 65100, Loss: 0.5143
Iteration 65200, Loss: 0.5143
Iteration 65300, Loss: 0.5143
Iteration 65400, Loss: 0.5143
Iteration 65500, Loss: 0.5143
Iteration 65600, Loss: 0.5143
Iteration 65700, Loss: 0.5143
Iteration 65800, Loss: 0.5143
Iteration 65900, Loss: 0.5143
Iteration 66000, Loss: 0.5143
Iteration 66100, Loss: 0.5143
Iteration 66200, Loss: 0.5143
Iteration 66300, Loss: 0.5143
Iteration 66400, Loss: 0.5143
Iteration 66500, Loss: 0.5143
Iteration 66600, Loss: 0.5143
Iteration 66700, Loss: 0.5143
Iteration 66800, Loss: 0.5143
Iteration 66900, Loss: 0.5143

### Hacer predicciones

**Límite de decisión**

$$
\sigma(X.\theta) \geq  0.5
\rightarrow
y_{pred} = 1
$$
$$
\sigma(X.\theta) < 0.5
\rightarrow
y_{pred} = 0
$$

In [40]:
def predict(X, theta):
  umbral = 0.5
  z = sigmoid(np.dot(X, theta))
  y = np.where(z >= umbral, 1, 0)
  return y
y_pred = predict(X_test, theta)
print(f"Predicciones: {y_pred}")
print(f"Real: {y_test}")

Predicciones: [0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0
 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0
 1 0 0 0 0]
Real: [0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 1 1 1 0 0 0
 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 1 1 0 1 0 0
 0 1 0 1 1 0 0 1 0 0 0 0 1 0 1 1 0 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 1 0
 1 0 0 0 0]

### Evaluación del modelo

**Matriz de confusión**

$$
\text{Confusion matrix}$$
$$
\begin{array}{|c|c|c|}
\hline
&\textbf{Positive} & \textbf{Negative} \\
\hline
\textbf{Positive} & TP & FP\\
\hline
\textbf{Negative} & FN & TN \\
\hline
\end{array}
$$

$TP: \text{ True positive}$

$TN: \text{ True negative}$

$FP: \text{ False positive}$

$FN: \text{ False negative}$

In [41]:
def confusssion_matriz(y_read, y_pred):
  true_positive = 0
  true_negative = 0
  false_positive = 0
  false_negative = 0
  #len(y_read) calcula dimension de datos de y_read
  for i in range(len(y_read)):
    if y_read[i] == 1 and y_pred[i] == 1:
      true_positive += 1
    if y_read[i] == 0 and y_pred[i] == 0:
      true_negative += 1
    if y_read[i] == 1 and y_pred[i] == 0:
      false_negative += 1
    if y_read[i] == 0 and y_pred[i] == 1:
      false_positive += 1
  table = np.array(([[true_positive, false_positive], [false_negative, true_negative]]))

  return table

In [42]:
matrixConf = confusssion_matriz(y_test, y_pred)
matrixConf_df = pd.DataFrame(matrixConf, columns = ["Positive","Negative"], index = ["Positive","Negative"])
matrixConf_df

          Positive  Negative
Positive        18         4
Negative        22        72

*Accuracy*

$$
Accuracy=\frac{TP+TN}{TP+FP+TN+FN}
$$

In [48]:
#accuracy mide cuantos aciertos tiene el modelo con respecto a los valores reales
tp = matrixConf[0,0]
fp = matrixConf[0,1]
fn = matrixConf[1,0]
tn = matrixConf[1,1]


accuracy = (tp + tn) / (tp + fp + tn + fn)
print(f"Accuracy: {accuracy:.5f}")

Accuracy: 0.77586

*Precision*

$$
Precision=\frac{TP}{TP+FP}
$$

In [44]:
precision = tp / (tp + fp)
print(f"Precision: {precision:.5f}")

Precision: 0.81818

*Recall (sensibilidad o tasa de verdaderos positivos)*

$$
Recall=\frac{TP}{TP+FN}
$$

In [45]:
recall = tp /(tp + fn)
print(f"Recall: {recall:.5f}")

Recall: 0.45000